image: gradle:8-jdk17

variables:
  version: 0.1.0

stages:
  - build
  - publish

before_script:
  - chmod u+x gradlew*

gradle:
  stage: build
  script:
    - mv $CONFIG_PROPERTIES src/main/resources/config.properties
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar

docker:
  image: docker:23-cli
  stage: publish
  dependencies:
    - gradle
  script:
    - docker login registry.gitlab.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t registry.gitlab.com/andret-discord-solutions/torphes .
    - docker tag torphes:latest registry.gitlab.com/andret-discord-solutions/torphes:v$version
    - docker push registry.gitlab.com/andret-discord-solutions/torphes:v$version
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "master"'
#      when: manual
#    - when: never
