image: gradle:8-jdk17

stages:
  - build
  - publish

before_script:
  - chmod u+x gradlew*

gradle:
  stage: build
  script:
    - mv $CONFIG_PROPERTIES src/main/resources/config.properties
    - ./gradlew build
    - version=$(gradle properties -q | grep "version:" | awk '{print $2}')
  artifacts:
    paths:
      - build/libs/*.jar

docker:
  image: docker:23-cli
  stage: publish
  dependencies:
    - gradle
  script:
    #    - docker image build -t torphes:latest .
    - echo $version
#    - docker tag torphes:latest andret-discord-solutions/torphes:v0.1.0
