image: gradle:8-jdk17

before_script:
  - chmod u+x gradlew*

gradle:
  script:
    - ls -laF src/main/resources
    - mv $CONFIG_PROPERTIES src/main/resources/config.properties
    - ls -laF src/main/resources
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
