name: Gradle CI + Release + Docker

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.ref.outputs.VERSION }}
      IS_TAG: ${{ steps.ref.outputs.IS_TAG }}
    steps:
      - id: ref
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
            echo "IS_TAG=true" >> "$GITHUB_OUTPUT"
          else
            echo "VERSION=" >> "$GITHUB_OUTPUT"
            echo "IS_TAG=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build with JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: [ prepare ]
    strategy:
      matrix:
        java: [ 21 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Make gradlew executable
        run: chmod u+x gradlew*

      - name: Write config.properties (opcjonalnie z secretu)
        run: printf "%s" "${{ secrets.CONFIG_PROPERTIES }}" > src/main/resources/config.properties

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-java-${{ needs.prepare.outputs.VERSION }}
          path: build/libs/*.jar

  release:
    name: Create a release ${{ github.ref_name }} and attach JARs
    runs-on: ubuntu-latest
    needs: [ prepare, build ]
    if: ${{ needs.prepare.outputs.IS_TAG == 'true' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Fetch matrix artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create a GitHub Release and attach JARs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: [ prepare, build ]
    if: ${{ needs.prepare.outputs.IS_TAG == 'true'}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts-java-${{ needs.prepare.outputs.VERSION }}
          path: build/libs

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: v
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ needs.prepare.outputs.VERSION }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.version=${{ needs.prepare.outputs.VERSION }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
